name: Pull Requests

on:
  pull_request:
    branches: [dev, staging, prod]

env:
  NODE_OPTIONS: --max_old_space_size=4096

jobs:
  build-test:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: 12

      - uses: actions/checkout@v2

      # 1. Install and cache dependencies.
      - uses: actions/cache@v2
        id: yarn-cache
        with:
          path: .yarn/cache
          key: yarn-${{ hashFiles('**/yarn.lock') }}

      - name: Install dependencies
        run: yarn --immutable

      # 2. Run static code analysis.
      - name: Check code formatting
        run: yarn prettier:check

      - name: ESLint
        run: yarn eslint

      # 3. Build custom packages (all packages located within the "packages" folder).
      - name: Build packages
        run: yarn webiny workspaces run build --folder packages

      # 4. Run unit tests.
      - name: Run tests
        run: yarn test
